### ISSUE TITLE
Texto generado incluye comillas extra

### ISSUE THREAD

**Issue by gonzalezgarcia** [pakitochus/generador_ayudas_aei#1]
Muchísimas gracias por la herramienta!

Al probarla con la convocatoria RyC de 2021, la parte del texto generado que hace referencia a fondos europeos aparece con unas comillas extra que creo se podrían eliminar.

Ejemplo: Grant RYC2021-033536-I funded by MICIU/AEI/10.13039/501100011033 and by **``European Union NextGenerationEU/PRTR''**

Navegador: Firefox
Sistema Operativo: MacOS

**Comment by pakitochus** [comment]
Pues el tema de las comillas es controvertido, porque en los textos de ejemplo aparecen con comillas, pero luego en el desglose del anexo I si salen sin comillas. Cuando programé esto pensaba que eran fijas, pero mirando tu comentario creo que sí van a ser la forma que tiene el que ha redactado el documento de decirnos o "esto" o "este otro" (un poco peculiar, la verdad). 

Creo que lo corrijo y lo marco. Thanks!
